version: 2.1
description: This is an inline job

orbs:
  expo-orb:
    jobs:
      install-expo:
        steps:
          - expo-io:
              greeting_name: <<parameters.greeting_name>>
    commands:
      expo-io:
        steps:
          - run: npm install expo-cli --global

workflows:
  build-test-deploy:
    docker:
      - image: node
    jobs:
      - expo-orb/install-expo
