version: 2.1
description: This is an inline job

orbs:
  expo-orb:
    jobs:
      install-expo:
        parameters:
          greeting_name:
            description: # a helpful description
            type: string
            default: olleh
        executor: my_inline_executor
        steps:
          - expo-io:
              greeting_name: <<parameters.greeting_name>>
    commands:
      expo-io:
        parameters:
          greeting_name:
            type: string
        steps:
          - run:
              name: NPM version
              command: npm --version
          - run:
              name: NODE version
              command: node --version
          - run:
              name: Install Expo.io
              command: npm install expo-cli --global
    executors:
      my_inline_executor:
        docker:
          - image: node:10.20.1

workflows:
  build-test-deploy:
    jobs:
      - expo-orb/install-expo:
          name: mybuild # best practice is to name each orb job
      - expo-orb/install-expo:
          name: mybuild2
          greeting_name: world
