version: 2.1
description: This is an inline job

orbs:
  expo-orb:
    jobs:
      my_inline_job:
        parameters:
          greeting_name:
            description: # a helpful description
            type: string
            default: olleh
        steps:
          - my_inline_command:
              greeting_name: <<parameters.greeting_name>>
    commands:
      my_inline_command:
        parameters:
          greeting_name:
            type: string
        steps:
          - run: sudo npm install expo-cli --global

workflows:
  build-test-deploy:
    docker:
      - image: node
    jobs:
      - expo-orb/my_inline_job:
          name: mybuild # best practice is to name each orb job
      - expo-orb/my_inline_job:
          name: mybuild2
          greeting_name: world
