version: 2

jobs:
  build:
    docker:
      image: node:10.20.1
    steps:
      - run:
          name: NPM version
          command: npm --version
      - run:
          name: NODE version
          command: node --version
      - run:
          name: Install Expo.io
          command: npm install expo-cli --global
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Print pakage json
          command: cat pakage-lock.json